---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    package:
      update_cache: yes
  
  - name: install apache and php package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
